# Generated by Django 4.0.3 on 2022-03-10 09:14

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('myblog', '0004_blogpagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='myblog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
